### ISSUE TITLE
long running process

### ISSUE THREAD

**Issue by tnguyen14** [zachlatta/fastprint#2]
Currently `npm start` will stop running when the session quits. What's the best way to keep this running in the background? Maybe something like `nohup`?

**Comment by tnguyen14** [comment]
I just thought of a better suggestion using https://www.npmjs.com/package/psy

It would be as simple as `psy start -n fastprint -- npm start`.

I just tested that and it works fine.

**Comment by zachlatta** [comment]
What if we just said something like `while true; do npm start; done`? That'll work in default bash, so no extra programs to install.

I'm personally going to set this up with systemd on my machine. Do you think it'd be out of scope to include setup instructions for that in the README?

**Comment by zachlatta** [comment]
Ah, actually scratch the bash suggestion. I totally misunderstand what psy does.

I'll add a section on running Fastprint in the background properly.

**Comment by tnguyen14** [comment]
Cool. Thanks. I understand not having to install a third party program.

I think it'd just be sufficient to mention the idea of running in the background. `psy` is just a suggestion on how to do that in a simple and easy to understand manner. It also handles logs by default. But any other way to do it is fine.

**Comment by zachlatta** [comment]
Okay cool, will add that!

## 

Zach Latta
Hack Club | zach@hackclub.io

**Comment by zachlatta** [comment]
Going to go ahead and close this because documentation on how to run Fastprint in the background is no longer planned.

If you're interested in adding it, a pull request is welcome :-).
