### ISSUE TITLE
 Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by Larbi75** [zachlatta/fastprint#4]
Hello

I have the following error when i lunch npm start

> fastprint@1.0.0 start /usr/local/src/fastprint
> node start.js

/usr/local/src/fastprint/start.js:6
let config = require('./config.js');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 3.16.0-4-586
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! fastprint@1.0.0 start: `node start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fastprint@1.0.0 start script 'node start.js'.
npm ERR! This is most likely a problem with the fastprint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fastprint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/src/fastprint/npm-debug.log

and the debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.14.9
3 info using node@v0.12.9
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart fastprint@1.0.0
7 info start fastprint@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info fastprint@1.0.0 Failed to exec start script
10 verbose stack Error: fastprint@1.0.0 start: `node start.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/
utils/lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/
utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1016:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:10
88:5)
11 verbose pkgid fastprint@1.0.0
12 verbose cwd /usr/local/src/fastprint
13 error Linux 3.16.0-4-586
14 error argv "/usr/bin/node" "/usr/bin/npm" "start"
15 error node v0.12.9
16 error npm  v2.14.9
17 error code ELIFECYCLE
18 error fastprint@1.0.0 start: `node start.js`
18 error Exit status 1
19 error Failed at the fastprint@1.0.0 start script 'node start.js'.
19 error This is most likely a problem with the fastprint package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node start.js
19 error You can get their info via:
19 error     npm owner ls fastprint
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

Any idea ?

Thanks again

**Comment by zachlatta** [comment]
Mmm, you're on Node v0.12.9, which I don't think supports the ES6
constructs used in Fastprint.

If you upgrade your Node version and try again, it should work. If it
doesn't, go ahead and reopen this issue with any logs.

On Fri, Apr 22, 2016 at 3:09 AM, 0blar notifications@github.com wrote:

> Hello
> 
> I have the following error when i lunch npm start
> 
> fastprint@1.0.0 start /usr/local/src/fastprint
> node start.js
> 
> /usr/local/src/fastprint/start.js:6
> let config = require('./config.js');
> ^^^
> SyntaxError: Unexpected strict mode reserved word
> at exports.runInThisContext (vm.js:73:16)
> at Module._compile (module.js:443:25)
> at Object.Module._extensions..js (module.js:478:10)
> at Module.load (module.js:355:32)
> at Function.Module._load (module.js:310:12)
> at Function.Module.runMain (module.js:501:10)
> at startup (node.js:129:16)
> at node.js:814:3
> 
> npm ERR! Linux 3.16.0-4-586
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
> npm ERR! node v0.12.9
> npm ERR! npm v2.14.9
> npm ERR! code ELIFECYCLE
> npm ERR! fastprint@1.0.0 start: node start.js
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the fastprint@1.0.0 start script 'node start.js'.
> npm ERR! This is most likely a problem with the fastprint package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! node start.js
> npm ERR! You can get their info via:
> npm ERR! npm owner ls fastprint
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! /usr/local/src/fastprint/npm-debug.log
> 
> and the debug log:
> 
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
> 2 info using npm@2.14.9
> 3 info using node@v0.12.9
> 4 verbose node symlink /usr/bin/node
> 5 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 6 info prestart fastprint@1.0.0
> 7 info start fastprint@1.0.0
> 8 verbose unsafe-perm in lifecycle true
> 9 info fastprint@1.0.0 Failed to exec start script
> 10 verbose stack Error: fastprint@1.0.0 start: node start.js
> 10 verbose stack Exit status 1
> 10 verbose stack at EventEmitter. (/usr/lib/node_modules/npm/lib/
> utils/lifecycle.js:214:16)
> 10 verbose stack at EventEmitter.emit (events.js:110:17)
> 10 verbose stack at ChildProcess. (/usr/lib/node_modules/npm/lib/
> utils/spawn.js:24:14)
> 10 verbose stack at ChildProcess.emit (events.js:110:17)
> 10 verbose stack at maybeClose (child_process.js:1016:16)
> 10 verbose stack at Process.ChildProcess._handle.onexit
> (child_process.js:10
> 88:5)
> 11 verbose pkgid fastprint@1.0.0
> 12 verbose cwd /usr/local/src/fastprint
> 13 error Linux 3.16.0-4-586
> 14 error argv "/usr/bin/node" "/usr/bin/npm" "start"
> 15 error node v0.12.9
> 16 error npm v2.14.9
> 17 error code ELIFECYCLE
> 18 error fastprint@1.0.0 start: node start.js
> 18 error Exit status 1
> 19 error Failed at the fastprint@1.0.0 start script 'node start.js'.
> 19 error This is most likely a problem with the fastprint package,
> 19 error not with npm itself.
> 19 error Tell the author that this fails on your system:
> 19 error node start.js
> 19 error You can get their info via:
> 19 error npm owner ls fastprint
> 19 error There is likely additional logging output above.
> 20 verbose exit [ 1, true ]
> 
> Any idea ?
> 
> Thanks again
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/zachlatta/fastprint/issues/4

## 

Zach Latta
Hack Club | zach@hackclub.com
